### ISSUE TITLE
pulldown-cmark panics when enabling both `heading-attributes` and `footnotes`

### ISSUE THREAD

**Issue by ytmimi** [pulldown-cmark/pulldown-cmark#963]
3abe8ca04211fe603a2f2bfa3d5231a241b180c3 crashes when running `./target/debug/pulldown-cmark  -F -H` on the following input:

```markdown
[^1]:
    *
      + > deeply nested setext header
        > [^2]
        > {.class}
        > ---------

[^2]: another footnote
```

<details>
<summary>Backtrace</summary>

```
thread 'main' panicked at pulldown-cmark/src/tree.rs:239:17:
assertion failed: self[child_ix].item.start < end_byte_ix
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/core/src/panicking.rs:141:5
   3: pulldown_cmark::tree::Tree<pulldown_cmark::parse::Item>::truncate_siblings
             at ./pulldown-cmark/src/tree.rs:239:17
   4: pulldown_cmark::firstpass::FirstPass::parse_setext_heading
             at ./pulldown-cmark/src/firstpass.rs:734:17
   5: pulldown_cmark::firstpass::FirstPass::parse_paragraph
             at ./pulldown-cmark/src/firstpass.rs:661:25
   6: pulldown_cmark::firstpass::FirstPass::parse_block
             at ./pulldown-cmark/src/firstpass.rs:434:9
   7: pulldown_cmark::firstpass::FirstPass::run
             at ./pulldown-cmark/src/firstpass.rs:76:18
   8: pulldown_cmark::firstpass::run_first_pass
             at ./pulldown-cmark/src/firstpass.rs:41:5
   9: pulldown_cmark::parse::Parser<F>::new_with_broken_link_callback
             at ./pulldown-cmark/src/parse.rs:270:34
  10: pulldown_cmark::pulldown_cmark
             at ./pulldown-cmark/src/main.rs:184:17
  11: pulldown_cmark::main
             at ./pulldown-cmark/src/main.rs:165:13
  12: core::ops::function::FnOnce::call_once
             at /rustc/f9b16149208c8a8a349c32813312716f6603eb6f/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

Changing the input slightly doesn't panic:

```markdown
[^1]:
    *
      + > deeply nested setext header
        > [^2] {.class}
        > ---------

[^2]: another footnote
```

**Comment by rhysd** [comment]
I could reduce the input (3abe8ca04211fe603a2f2bfa3d5231a241b180c3):

```markdown
> [^1]
> {.class}
> ===
```

Backtrace:

```
thread 'main' panicked at pulldown-cmark/src/tree.rs:239:17:
assertion failed: self[child_ix].item.start < end_byte_ix
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::panic
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:148:5
   3: pulldown_cmark::tree::Tree<pulldown_cmark::parse::Item>::truncate_siblings
             at ./pulldown-cmark/src/tree.rs:239:17
   4: pulldown_cmark::firstpass::FirstPass::parse_setext_heading
             at ./pulldown-cmark/src/firstpass.rs:734:17
   5: pulldown_cmark::firstpass::FirstPass::parse_paragraph
             at ./pulldown-cmark/src/firstpass.rs:661:25
   6: pulldown_cmark::firstpass::FirstPass::parse_block
             at ./pulldown-cmark/src/firstpass.rs:434:9
   7: pulldown_cmark::firstpass::FirstPass::run
             at ./pulldown-cmark/src/firstpass.rs:76:18
   8: pulldown_cmark::firstpass::run_first_pass
             at ./pulldown-cmark/src/firstpass.rs:41:5
   9: pulldown_cmark::parse::Parser<F>::new_with_broken_link_callback
             at ./pulldown-cmark/src/parse.rs:270:34
  10: pulldown_cmark::pulldown_cmark
             at ./pulldown-cmark/src/main.rs:184:17
  11: pulldown_cmark::main
             at ./pulldown-cmark/src/main.rs:165:13
  12: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
